In [1]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5,6])#array slicing
print(arr[0:5])
print(arr[4:])
print(arr[:-1])
print(arr[0:5:2])
print(arr[::2])

[1 2 3 4 5]
[5 6]
[1 2 3 4 5]
[1 3 5]
[1 3 5]


In [19]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[1,0:1])
print(arr2[0:2,2])
print(arr2[0:2,0:3])

[4]
[3 6]
[[1 2 3]
 [4 5 6]]
