In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])#ndarrays(List)

In [3]:
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr1 = np.array((1,2,3,4,5))#Tuple
arr

array([1, 2, 3, 4, 5])

In [5]:
#o-D array
arr2 = np.array(45)
print(arr2)
print(arr2.ndim)

45
0


In [6]:
#1-D array
arr3 = np.array([1,2,3,4,5,6])
print(arr3)
print(arr3.ndim)

[1 2 3 4 5 6]
1


In [7]:
#2-D array
arr4= np.array([[1,2,3],[4,5,6]])
print(arr4)
print(arr4.ndim)


[[1 2 3]
 [4 5 6]]
2


In [8]:
#3-D array
arr5 = np.array([[[1,2,3],[4,5,6]],[[3,2,1],[6,5,4]]])
print(arr5)
print(arr5.ndim)

[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [6 5 4]]]
3


In [9]:
arr6 = np.array([1,2,3,4,5,6],ndmin = 5)#Noofdimensions
print(arr6)
print(arr6.ndim)

[[[[[1 2 3 4 5 6]]]]]
5
